// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBuildDetails(arg1) {
  return window['go']['main']['App']['GetBuildDetails'](arg1);
}

export function GetISPInfo() {
  return window['go']['main']['App']['GetISPInfo']();
}

export function GetSessionData() {
  return window['go']['main']['App']['GetSessionData']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsWinwsRunning() {
  return window['go']['main']['App']['IsWinwsRunning']();
}

export function OpenAppData() {
  return window['go']['main']['App']['OpenAppData']();
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetFinlandFix(arg1) {
  return window['go']['main']['App']['SetFinlandFix'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
