// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBuildDetails(arg1:string):Promise<Record<string, any>>;

export function GetISPInfo():Promise<string>;

export function GetSessionData():Promise<string>;

export function GetSettings():Promise<main.AppSettings>;

export function IsWinwsRunning():Promise<boolean>;

export function OpenAppData():Promise<void>;

export function Reset():Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<string>;

export function SelectFolder():Promise<string>;

export function SetFinlandFix(arg1:boolean):Promise<string>;

export function Start(arg1:boolean):Promise<void>;

export function Stop():Promise<void>;
